services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres_container'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=bycodersdb'
    ports:
        - '5432:5432'